//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.05 at 09:53:27 PM EET 
//


package com.medicalcenter.Medicalcenter.schemas.school;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the medicalcenter.schemas.school package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: medicalcenter.schemas.school
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StudentDetailsRequest }
     * 
     */
    public StudentDetailsRequest createStudentDetailsRequest() {
        return new StudentDetailsRequest();
    }

    /**
     * Create an instance of {@link StudentDetailsResponse }
     * 
     */
    public StudentDetailsResponse createStudentDetailsResponse() {
        return new StudentDetailsResponse();
    }

    /**
     * Create an instance of {@link Student }
     * 
     */
    public Student createStudent() {
        return new Student();
    }

    /**
     * Create an instance of {@link ActivityDetailsRequest }
     * 
     */
    public ActivityDetailsRequest createActivityDetailsRequest() {
        return new ActivityDetailsRequest();
    }

    /**
     * Create an instance of {@link ActivityDetailsResponse }
     * 
     */
    public ActivityDetailsResponse createActivityDetailsResponse() {
        return new ActivityDetailsResponse();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link ActivityDetailsRequest2 }
     * 
     */
    public ActivityDetailsRequest2 createActivityDetailsRequest2() {
        return new ActivityDetailsRequest2();
    }

    /**
     * Create an instance of {@link ActivityDetailsResponse2 }
     * 
     */
    public ActivityDetailsResponse2 createActivityDetailsResponse2() {
        return new ActivityDetailsResponse2();
    }

    /**
     * Create an instance of {@link MedDayDetailsRequest }
     * 
     */
    public MedDayDetailsRequest createMedDayDetailsRequest() {
        return new MedDayDetailsRequest();
    }

    /**
     * Create an instance of {@link MedDayDetailsResponse }
     * 
     */
    public MedDayDetailsResponse createMedDayDetailsResponse() {
        return new MedDayDetailsResponse();
    }

    /**
     * Create an instance of {@link MedDay }
     * 
     */
    public MedDay createMedDay() {
        return new MedDay();
    }

    /**
     * Create an instance of {@link RecomandationDetailsRequest }
     * 
     */
    public RecomandationDetailsRequest createRecomandationDetailsRequest() {
        return new RecomandationDetailsRequest();
    }

    /**
     * Create an instance of {@link Recomandation }
     * 
     */
    public Recomandation createRecomandation() {
        return new Recomandation();
    }

}
